# spring:
#  config:
#    import: configserver:http://localhost:8087


 eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
        
 management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
 
  endpoint:
    health:
      show-details: always
 
 
 resilience4j:
    circuitbreaker:
     instances:
      aggregateDataCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
 
    retry:
      instances:
        aggregateDataRetry:
          max-attempts: 3
          wait-duration: 5s
 
    ratelimiter:
      instances:
        aggregateDataRateLimiter:
          limit-refresh-period: 4s
          limit-for-period: 2
          timeout-duration: 2s
